# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Source\miniprojects\part1\studyPyQt\addressBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 503)
        font = QtGui.QFont()
        font.setFamily("나눔고딕")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 16, 621, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 25, 60, 12))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.txtName = QtWidgets.QLineEdit(self.groupBox)
        self.txtName.setGeometry(QtCore.QRect(70, 20, 211, 20))
        self.txtName.setInputMethodHints(QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhPreferUppercase)
        self.txtName.setObjectName("txtName")
        self.txtPhone = QtWidgets.QLineEdit(self.groupBox)
        self.txtPhone.setGeometry(QtCore.QRect(70, 48, 211, 20))
        self.txtPhone.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.txtPhone.setObjectName("txtPhone")
        self.txtEmail = QtWidgets.QLineEdit(self.groupBox)
        self.txtEmail.setGeometry(QtCore.QRect(70, 75, 211, 20))
        self.txtEmail.setObjectName("txtEmail")
        self.txtAddr = QtWidgets.QLineEdit(self.groupBox)
        self.txtAddr.setGeometry(QtCore.QRect(70, 100, 211, 20))
        self.txtAddr.setObjectName("txtAddr")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 52, 60, 12))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(11, 78, 60, 12))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(12, 103, 60, 12))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.btnNew = QtWidgets.QPushButton(self.groupBox)
        self.btnNew.setGeometry(QtCore.QRect(456, 100, 75, 23))
        self.btnNew.setObjectName("btnNew")
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setGeometry(QtCore.QRect(530, 100, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 165, 621, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.stbCurrent = QtWidgets.QStatusBar(MainWindow)
        self.stbCurrent.setObjectName("stbCurrent")
        MainWindow.setStatusBar(self.stbCurrent)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "정보입력"))
        self.label.setText(_translate("MainWindow", "이      름  : "))
        self.label_2.setText(_translate("MainWindow", "전화번호 : "))
        self.label_3.setText(_translate("MainWindow", "이   메일  : "))
        self.label_4.setText(_translate("MainWindow", "주      소   : "))
        self.btnNew.setText(_translate("MainWindow", "신규"))
        self.btnSave.setText(_translate("MainWindow", "저장"))
